### ISSUE TITLE
Posible to support 64 bit?

### ISSUE THREAD

**Issue by dzungpv** [billthefarmer/ffts-android#1]
Google play now require support 64 bit processor, @billthefarmer can you support arm 64 bit?

**Comment by billthefarmer** [comment]
The original [ffts](https://github.com/anthonix/ffts) has references to arm64, but the actual code is missing. I also found it wasn't so fast as to make a significant difference to my apps using a java fft.

**Comment by dzungpv** [comment]
@billthefarmer Thank you, i try to build arm64 but failed. What is the name of the pure java lib you use?

**Comment by billthefarmer** [comment]
I don't use a library, it's some code I found on the internet years ago which works very well... [fftr](https://github.com/billthefarmer/tuner/blob/master/src/main/java/org/billthefarmer/tuner/MainActivity.java#L1688). You also need the code for [Complex](https://github.com/billthefarmer/tuner/blob/master/src/main/java/org/billthefarmer/tuner/MainActivity.java#L1796). It only supports power of two sized arrays.
